import 'dart:convert';
import 'dart:developer' as developer;

import 'package:http/http.dart' as http;

import '../entities/patient_caregiver_link_entity.dart';
import '../entities/patient_hash_entity.dart';
import '../services/api_config.dart';

class LinkPatientCaregiver {
  final String baseUrl;
  final String userHash;
  final http.Client _client;
  final bool _ownsClient;

  LinkPatientCaregiver({
    this.baseUrl = ApiConfig.baseUrl,
    this.userHash = PatientHash.defaultPatientHash,
    http.Client? client,
  })  : _client = client ?? http.Client(),
        _ownsClient = client == null;

  // Function Name: requestPatientCaregiverLink
  // Description:
  // - Class diagram compatible wrapper for the patient-caregiver link page.
  // Returns:
  // - Active links for the current user hash.
  Future<List<PatientCaregiverLink>> requestPatientCaregiverLink() {
    return requestLinkPage();
  }

  // Function Name: requestLinkPage
  // Description:
  // - Reads active patient-caregiver links for the current user hash.
  // Returns:
  // - Active links for the current user hash.
  Future<List<PatientCaregiverLink>> requestLinkPage() async {
    try {
      final response = await _client
          .get(_buildLinkUri('link/list'))
          .timeout(const Duration(seconds: 30));
      final responseBody = utf8.decode(response.bodyBytes);

      if (response.statusCode != 200) {
        throw StateError(
          'Link lookup failed (${response.statusCode}): '
          '${_extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = _decodeMap(responseBody);
      return _decodeLinkList(decodedData['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-caregiver link lookup failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Link lookup failed.');
    }
  }

  // Function Name: requestPatientCode
  // Description:
  // - Requests a temporary patient code for caregiver registration.
  // Returns:
  // - Generated patient code.
  Future<String> requestPatientCode() async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/code'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({'patient_hash': userHash}),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = utf8.decode(response.bodyBytes);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient code creation failed (${response.statusCode}): '
          '${_extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = _decodeMap(responseBody);
      final rawData = decodedData['data'];
      if (rawData is Map) {
        return (rawData['patient_code'] ?? '').toString();
      }
      throw StateError('Server response did not include a patient code.');
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient code request failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient code creation failed.');
    }
  }

  // Function Name: registerPatientCode
  // Description:
  // - Registers the current caregiver hash with a patient code.
  // Parameters:
  // - patientCode: Temporary code generated by the patient.
  // Returns:
  // - Created patient-caregiver link.
  Future<PatientCaregiverLink> registerPatientCode(String patientCode) async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/register'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({
              'caregiver_hash': userHash,
              'patient_code': patientCode,
            }),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = utf8.decode(response.bodyBytes);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient registration failed (${response.statusCode}): '
          '${_extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(_decodeMap(responseBody)['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient registration failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient registration failed.');
    }
  }

  // Function Name: requestUnlink
  // Description:
  // - Removes one patient-caregiver link for the current user hash.
  // Parameters:
  // - linkId: Patient-caregiver link identifier.
  // Returns:
  // - Updated patient-caregiver link.
  Future<PatientCaregiverLink> requestUnlink(int linkId) async {
    try {
      final response = await _client
          .delete(_buildLinkUri('link/$linkId'))
          .timeout(const Duration(seconds: 30));
      final responseBody = utf8.decode(response.bodyBytes);

      if (response.statusCode != 200) {
        throw StateError(
          'Unlink failed (${response.statusCode}): '
          '${_extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(_decodeMap(responseBody)['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-caregiver unlink failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Unlink failed.');
    }
  }

  PatientCaregiverLink _decodeSingleLink(dynamic rawItem) {
    if (rawItem is Map) {
      return PatientCaregiverLink.fromJson(Map<String, dynamic>.from(rawItem));
    }
    throw StateError('Server response did not include a link.');
  }

  List<PatientCaregiverLink> _decodeLinkList(dynamic rawItems) {
    if (rawItems is! List) {
      return [];
    }

    return rawItems
        .whereType<Map>()
        .map((item) =>
            PatientCaregiverLink.fromJson(Map<String, dynamic>.from(item)))
        .toList(growable: false);
  }

  Map<String, dynamic> _decodeMap(String responseBody) {
    final dynamic decodedData = jsonDecode(responseBody);
    if (decodedData is Map<String, dynamic>) {
      return decodedData;
    }
    throw StateError('Server response format was invalid.');
  }

  String _extractErrorDetail(String responseBody) {
    try {
      final decodedError = _decodeMap(responseBody);
      if (decodedError['detail'] != null) {
        return decodedError['detail'].toString();
      }
    } catch (_) {
      return responseBody;
    }
    return responseBody;
  }

  Uri _buildLinkUri(String path) {
    return Uri.parse('$baseUrl/$path').replace(
      queryParameters: {'user_hash': userHash},
    );
  }

  void dispose() {
    if (_ownsClient) {
      _client.close();
    }
  }
}
