import 'dart:convert';
import 'dart:developer' as developer;

import 'package:http/http.dart' as http;

import '../entities/patient_caregiver_link_entity.dart';
import '../entities/patient_hash_entity.dart';
import '../services/api_config.dart';
import '../services/authenticated_api_client.dart';
import '../services/api_response_parser.dart';

// 파일명: link_patient_caregiver_control.dart
// 역할: 환자-보호자 연동 API와 프론트 화면을 연결한다.

// 클래스명: LinkPatientCaregiver
// 역할: 환자 코드 생성, 보호자 등록, 연동 해제를 처리한다.
// 주요 책임:
// - 현재 사용자 해시 기준의 연동 목록을 조회한다.
// - 환자 측 임시 연동 코드를 생성한다.
// - 보호자 측에서 환자 코드를 등록하거나 기존 연동을 해제한다.
class LinkPatientCaregiver {
  final String baseUrl;
  final String userHash;
  final http.Client _client;
  final bool _ownsClient;

  LinkPatientCaregiver({
    this.baseUrl = ApiConfig.baseUrl,
    this.userHash = PatientHash.defaultPatientHash,
    http.Client? client,
  }) : _client = client ?? AuthenticatedApiClient(),
       _ownsClient = client == null;

  // Function Name: requestLinkScreen
  // Description:
  // - Reads active patient-caregiver links for the current user hash.
  // Returns:
  // - Active links for the current user hash.
  Future<List<PatientCaregiverLink>> requestLinkScreen() async {
    try {
      final response = await _client
          .get(_buildLinkUri('link/list'))
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Link lookup failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = ApiResponseParser.decodeMap(responseBody);
      return _decodeLinkList(decodedData['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-caregiver link lookup failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Link lookup failed.');
    }
  }

  // Function Name: generatePatientHash
  // Description:
  // - Requests a temporary patient code for caregiver registration.
  // Returns:
  // - Generated patient code.
  Future<PatientLinkCode> generatePatientHash() async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/code'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({'patient_hash': userHash}),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient code creation failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = ApiResponseParser.decodeMap(responseBody);
      final rawData = decodedData['data'];
      if (rawData is Map) {
        return PatientLinkCode.fromJson(Map<String, dynamic>.from(rawData));
      }
      throw StateError('Server response did not include a patient code.');
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient code request failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient code creation failed.');
    }
  }

  // Function Name: requestPatientCaregiverLink
  // Description:
  // - Registers the current caregiver hash with a patient code.
  // Parameters:
  // - patientCode: Temporary code generated by the patient.
  // Returns:
  // - Created patient-caregiver link.
  Future<PatientCaregiverLink> requestPatientCaregiverLink(
    String patientCode,
  ) async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/register'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({
              'caregiver_hash': userHash,
              'patient_code': patientCode,
            }),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient registration failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(
        ApiResponseParser.decodeMap(responseBody)['data'],
      );
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient registration failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient registration failed.');
    }
  }

  // 함수이름: savePatientAlias
  // 함수역할:
  // - 현재 보호자가 지정한 환자 표시 이름을 서버 연동 관계에 저장한다.
  // - 빈 문자열은 별칭을 삭제하고 기본 표시 이름으로 되돌린다.
  Future<PatientCaregiverLink> savePatientAlias({
    required int linkId,
    required String patientAlias,
  }) async {
    try {
      final response = await _client
          .patch(
            _buildLinkUri('link/$linkId/patient-alias'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({'patient_alias': patientAlias}),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);
      if (response.statusCode != 200) {
        throw StateError(
          'Patient alias save failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }
      return _decodeSingleLink(
        ApiResponseParser.decodeMap(responseBody)['data'],
      );
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        '환자 표시 이름 서버 저장에 실패했습니다.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient alias save failed.');
    }
  }

  // Function Name: requestUnlink
  // Description:
  // - Removes one patient-caregiver link for the current user hash.
  // Parameters:
  // - linkId: Patient-caregiver link identifier.
  // Returns:
  // - Updated patient-caregiver link.
  Future<PatientCaregiverLink> requestUnlink(int linkId) async {
    try {
      final response = await _client
          .delete(_buildLinkUri('link/$linkId'))
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Unlink failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(
        ApiResponseParser.decodeMap(responseBody)['data'],
      );
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-caregiver unlink failed.',
        name: 'LinkPatientCaregiver',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Unlink failed.');
    }
  }

  PatientCaregiverLink _decodeSingleLink(dynamic rawItem) {
    if (rawItem is Map) {
      return PatientCaregiverLink.fromJson(Map<String, dynamic>.from(rawItem));
    }
    throw StateError('Server response did not include a link.');
  }

  List<PatientCaregiverLink> _decodeLinkList(dynamic rawItems) {
    if (rawItems is! List) {
      return [];
    }

    return rawItems
        .whereType<Map>()
        .map(
          (item) =>
              PatientCaregiverLink.fromJson(Map<String, dynamic>.from(item)),
        )
        .toList(growable: false);
  }

  Uri _buildLinkUri(String path) {
    return Uri.parse(
      '$baseUrl/$path',
    ).replace(queryParameters: {'user_hash': userHash});
  }

  void dispose() {
    if (_ownsClient) {
      _client.close();
    }
  }
}
