import 'dart:convert';
import 'dart:developer' as developer;

import 'package:http/http.dart' as http;

import '../entities/patient_guardian_link_entity.dart';
import '../entities/patient_hash_entity.dart';
import '../services/api_config.dart';
import '../services/api_response_parser.dart';

// 파일명: patient_guardian_link_control.dart
// 역할: 환자-보호자 연동 API와 프론트 화면을 연결한다.

// 클래스명: PatientGuardianLinkControl
// 역할: 환자 코드 생성, 보호자 등록, 연동 해제를 처리한다.
// 주요 책임:
// - 현재 사용자 해시 기준의 연동 목록을 조회한다.
// - 환자 측 임시 연동 코드를 생성한다.
// - 보호자 측에서 환자 코드를 등록하거나 기존 연동을 해제한다.
class PatientGuardianLinkControl {
  final String baseUrl;
  final String userHash;
  final http.Client _client;
  final bool _ownsClient;

  PatientGuardianLinkControl({
    this.baseUrl = ApiConfig.baseUrl,
    this.userHash = PatientHash.defaultPatientHash,
    http.Client? client,
  })  : _client = client ?? http.Client(),
        _ownsClient = client == null;

  // Function Name: requestPatientGuardianLink
  // Description:
  // - Class diagram compatible wrapper for the patient-guardian link page.
  // Returns:
  // - Active links for the current user hash.
  Future<List<PatientGuardianLink>> requestPatientGuardianLink() {
    return requestLinkPage();
  }

  // Function Name: requestLinkPage
  // Description:
  // - Reads active patient-guardian links for the current user hash.
  // Returns:
  // - Active links for the current user hash.
  Future<List<PatientGuardianLink>> requestLinkPage() async {
    try {
      final response = await _client
          .get(_buildLinkUri('link/list'))
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Link lookup failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = ApiResponseParser.decodeMap(responseBody);
      return _decodeLinkList(decodedData['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-guardian link lookup failed.',
        name: 'PatientGuardianLinkControl',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Link lookup failed.');
    }
  }

  // Function Name: requestPatientCode
  // Description:
  // - Requests a temporary patient code for guardian registration.
  // Returns:
  // - Generated patient code.
  Future<String> requestPatientCode() async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/code'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({'patient_hash': userHash}),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient code creation failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      final decodedData = ApiResponseParser.decodeMap(responseBody);
      final rawData = decodedData['data'];
      if (rawData is Map) {
        return (rawData['patient_code'] ?? '').toString();
      }
      throw StateError('Server response did not include a patient code.');
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient code request failed.',
        name: 'PatientGuardianLinkControl',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient code creation failed.');
    }
  }

  // Function Name: createPatientCode
  // Description:
  // - Class diagram compatible wrapper for creating a patient link code.
  // Returns:
  // - Generated patient code.
  Future<String> createPatientCode() {
    return requestPatientCode();
  }

  // Function Name: registerPatientCode
  // Description:
  // - Registers the current guardian hash with a patient code.
  // Parameters:
  // - patientCode: Temporary code generated by the patient.
  // Returns:
  // - Created patient-guardian link.
  Future<PatientGuardianLink> registerPatientCode(String patientCode) async {
    try {
      final response = await _client
          .post(
            Uri.parse('$baseUrl/link/register'),
            headers: const {'Content-Type': 'application/json'},
            body: jsonEncode({
              'guardian_hash': userHash,
              'patient_code': patientCode,
            }),
          )
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Patient registration failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(
          ApiResponseParser.decodeMap(responseBody)['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient registration failed.',
        name: 'PatientGuardianLinkControl',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Patient registration failed.');
    }
  }

  // Function Name: requestUnlink
  // Description:
  // - Removes one patient-guardian link for the current user hash.
  // Parameters:
  // - linkId: Patient-guardian link identifier.
  // Returns:
  // - Updated patient-guardian link.
  Future<PatientGuardianLink> requestUnlink(int linkId) async {
    try {
      final response = await _client
          .delete(_buildLinkUri('link/$linkId'))
          .timeout(const Duration(seconds: 30));
      final responseBody = ApiResponseParser.decodeBody(response);

      if (response.statusCode != 200) {
        throw StateError(
          'Unlink failed (${response.statusCode}): '
          '${ApiResponseParser.extractErrorDetail(responseBody)}',
        );
      }

      return _decodeSingleLink(
          ApiResponseParser.decodeMap(responseBody)['data']);
    } on StateError {
      rethrow;
    } catch (error, stackTrace) {
      developer.log(
        'Patient-guardian unlink failed.',
        name: 'PatientGuardianLinkControl',
        error: error,
        stackTrace: stackTrace,
      );
      throw StateError('Unlink failed.');
    }
  }

  // Function Name: deletePatientGuardianLink
  // Description:
  // - Class diagram compatible wrapper for deleting a patient-guardian link.
  // Parameters:
  // - linkId: Patient-guardian link identifier.
  // Returns:
  // - Updated patient-guardian link.
  Future<PatientGuardianLink> deletePatientGuardianLink(int linkId) {
    return requestUnlink(linkId);
  }

  PatientGuardianLink _decodeSingleLink(dynamic rawItem) {
    if (rawItem is Map) {
      return PatientGuardianLink.fromJson(Map<String, dynamic>.from(rawItem));
    }
    throw StateError('Server response did not include a link.');
  }

  List<PatientGuardianLink> _decodeLinkList(dynamic rawItems) {
    if (rawItems is! List) {
      return [];
    }

    return rawItems
        .whereType<Map>()
        .map((item) =>
            PatientGuardianLink.fromJson(Map<String, dynamic>.from(item)))
        .toList(growable: false);
  }

  Uri _buildLinkUri(String path) {
    return Uri.parse('$baseUrl/$path').replace(
      queryParameters: {'user_hash': userHash},
    );
  }

  void dispose() {
    if (_ownsClient) {
      _client.close();
    }
  }
}
