# File Name: medication.py
# Role: Defines medication request and response DTOs.

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field

from entities.medication_detail_entity import MedicationDetail
from entities.patient_hash_entity import DEFAULT_PATIENT_HASH


# Class Name: MedicationRequest
# Role: Request DTO for medication lookup.
# Attributes:
#   - extracted_text: Raw medication text extracted by the frontend or analysis flow.
class MedicationRequest(BaseModel):
    extracted_text: Optional[str] = None


# Class Name: SavedMedicationCreate
# Role: Request DTO for saving a medication snapshot.
# Attributes:
#   - patient_hash: Patient ownership key used for saved medication scoping.
#   - item_name: Medication item name.
#   - efficacy: Medication efficacy summary.
#   - use_method: Medication use method summary.
#   - warning_message: Medication warning summary.
#   - dosage_per_time: Optional dose per administration from prescription analysis.
#   - daily_frequency: Optional daily frequency from prescription analysis.
#   - total_days: Optional total medication days from prescription analysis.
#   - ai_guide: Optional AI-generated patient guide.
class SavedMedicationCreate(BaseModel):
    patient_hash: str = DEFAULT_PATIENT_HASH
    prescription_date: Optional[date] = None
    item_name: str
    efficacy: str
    use_method: str
    warning_message: str
    dosage_per_time: Optional[str] = None
    daily_frequency: Optional[str] = None
    total_days: Optional[str] = None
    image_url: Optional[str] = None
    ai_guide: Optional[str] = None


# Class Name: MedicationStatusUpdate
# Role: Request DTO for updating today's medication completion status.
# Attributes:
#   - medication_status: Whether the medication is completed.
#   - slot_key: Optional time-slot key for per-dose completion updates.
class MedicationStatusUpdate(BaseModel):
    medication_status: bool
    slot_key: Optional[str] = None


# Class Name: PatientCodeCreate
# Role: Request DTO for creating a temporary patient link code.
# Attributes:
#   - patient_hash: Patient ownership key encoded in the generated link code.
class PatientCodeCreate(BaseModel):
    patient_hash: str = DEFAULT_PATIENT_HASH


# Class Name: PatientCodeRegister
# Role: Request DTO for registering a caregiver through a patient code.
# Attributes:
#   - caregiver_hash: Caregiver ownership key.
#   - patient_code: Temporary patient link code generated by the patient.
class PatientCodeRegister(BaseModel):
    caregiver_hash: str = DEFAULT_PATIENT_HASH
    patient_code: str


# Class Name: MedicationResponse
# Role: Response DTO for medication lookup results.
# Attributes:
#   - success: Whether lookup found data.
#   - message: User-facing result message.
#   - data: MedicationDetail result list.
class MedicationResponse(BaseModel):
    success: bool
    message: str
    data: list[MedicationDetail] = Field(default_factory=list)
