# File Name: medication.py
# Role: Defines medication request and response DTOs.

from datetime import date
from typing import Optional

from pydantic import AliasChoices, BaseModel, ConfigDict, Field

from entities.medication_detail_entity import MedicationDetail
from entities.patient_hash_entity import DEFAULT_PATIENT_HASH


# Class Name: MedicationRequest
# Role: Request DTO for medication lookup.
# Attributes:
#   - extracted_text: Raw medication text extracted by the frontend or analysis flow.
class MedicationRequest(BaseModel):
    extracted_text: Optional[str] = None


# Class Name: SavedMedicationCreate
# Role: Request DTO for saving a medication snapshot.
# Attributes:
#   - patient_hash: Patient ownership key used for saved medication scoping.
#   - item_name: Medication item name.
#   - efficacy: Medication efficacy summary.
#   - use_method: Medication use method summary.
#   - warning_message: Medication warning summary.
#   - dosage_per_time: Optional dose per administration from prescription analysis.
#   - daily_frequency: Optional daily frequency from prescription analysis.
#   - total_days: Optional total medication days from prescription analysis.
#   - ai_guide: Optional AI-generated patient guide.
class SavedMedicationCreate(BaseModel):
    patient_hash: str = DEFAULT_PATIENT_HASH
    prescription_date: Optional[date] = None
    item_name: str
    efficacy: str
    use_method: str
    warning_message: str
    dosage_per_time: Optional[str] = None
    daily_frequency: Optional[str] = None
    total_days: Optional[str] = None
    image_url: Optional[str] = None
    ai_guide: Optional[str] = None


# Class Name: MedicationStatusUpdate
# Role: Request DTO for updating today's medication completion status.
# Attributes:
#   - medication_status: Whether the medication is completed.
#   - slot_key: Optional time-slot key for per-dose completion updates.
class MedicationStatusUpdate(BaseModel):
    medication_status: bool
    slot_key: Optional[str] = None


# Class Name: MedicationAlarmUpdate
# Role: Request DTO for saving one medication alarm setting.
# Attributes:
#   - hour: 24-hour local alarm hour.
#   - minute: Local alarm minute.
class MedicationAlarmUpdate(BaseModel):
    hour: int
    minute: int = 0


# Class Name: GuardianAlertUpdate
# Role: Request DTO for updating guardian alert setting state.
# Attributes:
#   - is_enabled: Boolean toggle value from the Flutter UI.
#   - alert_option: UML alert option string such as enable or disable.
class GuardianAlertUpdate(BaseModel):
    is_enabled: Optional[bool] = Field(
        default=None,
        validation_alias=AliasChoices("is_enabled", "enabled"),
    )
    alert_option: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("alert_option", "alertOption", "option"),
    )


# Class Name: UserSettingUpdate
# Role: Request DTO for saving user display and reading settings.
# Attributes:
#   - font_size: Selected display font size.
#   - reading_speed: Selected voice/reading speed multiplier.
#   - language: Selected language code.
class UserSettingUpdate(BaseModel):
    font_size: int
    reading_speed: float
    language: str


# Class Name: VoiceGuideRequest
# Role: Request DTO for medication voice guide generation.
# Attributes:
#   - item_name: Medication item name.
#   - usage_method: Medication use method summary.
#   - warning: Medication warning summary.
#   - language: Selected language code.
class VoiceGuideRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    item_name: str = ""
    usage_method: str = Field(
        default="",
        validation_alias=AliasChoices("usage_method", "use_method"),
    )
    warning: str = Field(
        default="",
        validation_alias=AliasChoices("warning", "warning_message"),
    )
    language: str = "ko"

    def to_medication_detail(self) -> MedicationDetail:
        return MedicationDetail(
            item_name=self.item_name,
            efficacy="",
            use_method=self.usage_method,
            warning_message=self.warning,
        )


# Class Name: PatientCodeCreate
# Role: Request DTO for creating a temporary patient link code.
# Attributes:
#   - patient_hash: Patient ownership key encoded in the generated link code.
class PatientCodeCreate(BaseModel):
    patient_hash: str = DEFAULT_PATIENT_HASH


# Class Name: PatientCodeRegister
# Role: Request DTO for registering a guardian through a patient code.
# Attributes:
#   - guardian_hash: Guardian ownership key.
#   - patient_code: Temporary patient link code generated by the patient.
class PatientCodeRegister(BaseModel):
    guardian_hash: str = Field(
        default=DEFAULT_PATIENT_HASH,
        validation_alias=AliasChoices("guardian_hash", "caregiver_hash"),
    )
    patient_code: str


# Class Name: MedicationResponse
# Role: Response DTO for medication lookup results.
# Attributes:
#   - success: Whether lookup found data.
#   - message: User-facing result message.
#   - data: MedicationDetail result list.
class MedicationResponse(BaseModel):
    success: bool
    message: str
    data: list[MedicationDetail] = Field(default_factory=list)
