"""create current schema

Revision ID: a4f66c9a7d0b
Revises:
Create Date: 2026-07-20 17:11:16.277616
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a4f66c9a7d0b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_approval_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_seq', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('normalized_item_name', sa.String(), nullable=False),
    sa.Column('entp_name', sa.String(), nullable=True),
    sa.Column('main_ingredient', sa.Text(), nullable=True),
    sa.Column('efficacy_doc', sa.Text(), nullable=True),
    sa.Column('use_method_doc', sa.Text(), nullable=True),
    sa.Column('warning_doc', sa.Text(), nullable=True),
    sa.Column('summary_efficacy', sa.Text(), nullable=True),
    sa.Column('summary_use_method', sa.Text(), nullable=True),
    sa.Column('summary_warning_message', sa.Text(), nullable=True),
    sa.Column('ai_guide', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_approval_infos_id'), 'drug_approval_infos', ['id'], unique=False)
    op.create_index(op.f('ix_drug_approval_infos_item_name'), 'drug_approval_infos', ['item_name'], unique=False)
    op.create_index(op.f('ix_drug_approval_infos_item_seq'), 'drug_approval_infos', ['item_seq'], unique=True)
    op.create_index(op.f('ix_drug_approval_infos_normalized_item_name'), 'drug_approval_infos', ['normalized_item_name'], unique=False)
    op.create_table('drug_basic_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_seq', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('normalized_item_name', sa.String(), nullable=False),
    sa.Column('entp_name', sa.String(), nullable=True),
    sa.Column('efficacy', sa.Text(), nullable=True),
    sa.Column('use_method', sa.Text(), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('interaction', sa.Text(), nullable=True),
    sa.Column('side_effect', sa.Text(), nullable=True),
    sa.Column('deposit_method', sa.Text(), nullable=True),
    sa.Column('ai_guide', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_basic_infos_id'), 'drug_basic_infos', ['id'], unique=False)
    op.create_index(op.f('ix_drug_basic_infos_item_name'), 'drug_basic_infos', ['item_name'], unique=False)
    op.create_index(op.f('ix_drug_basic_infos_item_seq'), 'drug_basic_infos', ['item_seq'], unique=True)
    op.create_index(op.f('ix_drug_basic_infos_normalized_item_name'), 'drug_basic_infos', ['normalized_item_name'], unique=False)
    op.create_table('guardian_alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_hash', sa.String(), nullable=False),
    sa.Column('patient_hash', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('alert_option', sa.String(), server_default='disable', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_hash', 'patient_hash', name='uq_guardian_alert_setting_scope')
    )
    op.create_index(op.f('ix_guardian_alert_settings_guardian_hash'), 'guardian_alert_settings', ['guardian_hash'], unique=False)
    op.create_index(op.f('ix_guardian_alert_settings_id'), 'guardian_alert_settings', ['id'], unique=False)
    op.create_index(op.f('ix_guardian_alert_settings_patient_hash'), 'guardian_alert_settings', ['patient_hash'], unique=False)
    op.create_table('health_recommendation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), server_default='local_patient', nullable=False),
    sa.Column('recommendation_key', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_recommendation_cache_id'), 'health_recommendation_cache', ['id'], unique=False)
    op.create_index(op.f('ix_health_recommendation_cache_patient_hash'), 'health_recommendation_cache', ['patient_hash'], unique=False)
    op.create_index(op.f('ix_health_recommendation_cache_recommendation_key'), 'health_recommendation_cache', ['recommendation_key'], unique=False)
    op.create_table('medication_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_medication_id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), server_default='local_patient', nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('slot_key', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_medication_id', 'patient_hash', 'schedule_date', 'slot_key', name='uq_medication_completion_slot')
    )
    op.create_index(op.f('ix_medication_completions_id'), 'medication_completions', ['id'], unique=False)
    op.create_index(op.f('ix_medication_completions_patient_hash'), 'medication_completions', ['patient_hash'], unique=False)
    op.create_index(op.f('ix_medication_completions_saved_medication_id'), 'medication_completions', ['saved_medication_id'], unique=False)
    op.create_index(op.f('ix_medication_completions_schedule_date'), 'medication_completions', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_medication_completions_slot_key'), 'medication_completions', ['slot_key'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), server_default='local_patient', nullable=False),
    sa.Column('slot_key', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), server_default='8', nullable=False),
    sa.Column('minute', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_hash', 'slot_key', name='uq_notification_setting_slot')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_notification_settings_patient_hash'), 'notification_settings', ['patient_hash'], unique=False)
    op.create_index(op.f('ix_notification_settings_slot_key'), 'notification_settings', ['slot_key'], unique=False)
    op.create_table('patient_caregiver_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), nullable=False),
    sa.Column('caregiver_hash', sa.String(), nullable=False),
    sa.Column('linked', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_hash', 'caregiver_hash', name='uq_patient_caregiver_link_pair')
    )
    op.create_index(op.f('ix_patient_caregiver_links_caregiver_hash'), 'patient_caregiver_links', ['caregiver_hash'], unique=False)
    op.create_index(op.f('ix_patient_caregiver_links_id'), 'patient_caregiver_links', ['id'], unique=False)
    op.create_index(op.f('ix_patient_caregiver_links_patient_hash'), 'patient_caregiver_links', ['patient_hash'], unique=False)
    op.create_table('patient_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), nullable=False),
    sa.Column('patient_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('caregiver_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_link_codes_caregiver_hash'), 'patient_link_codes', ['caregiver_hash'], unique=False)
    op.create_index(op.f('ix_patient_link_codes_id'), 'patient_link_codes', ['id'], unique=False)
    op.create_index(op.f('ix_patient_link_codes_patient_code'), 'patient_link_codes', ['patient_code'], unique=True)
    op.create_index(op.f('ix_patient_link_codes_patient_hash'), 'patient_link_codes', ['patient_hash'], unique=False)
    op.create_table('saved_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_hash', sa.String(), server_default='local_patient', nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=True),
    sa.Column('item_seq', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('efficacy', sa.String(), nullable=True),
    sa.Column('use_method', sa.String(), nullable=True),
    sa.Column('warning_message', sa.String(), nullable=True),
    sa.Column('dosage_per_time', sa.String(), nullable=True),
    sa.Column('daily_frequency', sa.String(), nullable=True),
    sa.Column('total_days', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('medication_status', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('medication_status_date', sa.Date(), nullable=True),
    sa.Column('ai_guide', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_medications_id'), 'saved_medications', ['id'], unique=False)
    op.create_index(op.f('ix_saved_medications_item_name'), 'saved_medications', ['item_name'], unique=False)
    op.create_index(op.f('ix_saved_medications_item_seq'), 'saved_medications', ['item_seq'], unique=False)
    op.create_index(op.f('ix_saved_medications_patient_hash'), 'saved_medications', ['patient_hash'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(), server_default='local_patient', nullable=False),
    sa.Column('font_size', sa.Integer(), server_default='16', nullable=False),
    sa.Column('reading_speed', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('language', sa.String(), server_default='ko', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_hash'), 'user_settings', ['user_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_hash'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_saved_medications_patient_hash'), table_name='saved_medications')
    op.drop_index(op.f('ix_saved_medications_item_seq'), table_name='saved_medications')
    op.drop_index(op.f('ix_saved_medications_item_name'), table_name='saved_medications')
    op.drop_index(op.f('ix_saved_medications_id'), table_name='saved_medications')
    op.drop_table('saved_medications')
    op.drop_index(op.f('ix_patient_link_codes_patient_hash'), table_name='patient_link_codes')
    op.drop_index(op.f('ix_patient_link_codes_patient_code'), table_name='patient_link_codes')
    op.drop_index(op.f('ix_patient_link_codes_id'), table_name='patient_link_codes')
    op.drop_index(op.f('ix_patient_link_codes_caregiver_hash'), table_name='patient_link_codes')
    op.drop_table('patient_link_codes')
    op.drop_index(op.f('ix_patient_caregiver_links_patient_hash'), table_name='patient_caregiver_links')
    op.drop_index(op.f('ix_patient_caregiver_links_id'), table_name='patient_caregiver_links')
    op.drop_index(op.f('ix_patient_caregiver_links_caregiver_hash'), table_name='patient_caregiver_links')
    op.drop_table('patient_caregiver_links')
    op.drop_index(op.f('ix_notification_settings_slot_key'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_patient_hash'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_medication_completions_slot_key'), table_name='medication_completions')
    op.drop_index(op.f('ix_medication_completions_schedule_date'), table_name='medication_completions')
    op.drop_index(op.f('ix_medication_completions_saved_medication_id'), table_name='medication_completions')
    op.drop_index(op.f('ix_medication_completions_patient_hash'), table_name='medication_completions')
    op.drop_index(op.f('ix_medication_completions_id'), table_name='medication_completions')
    op.drop_table('medication_completions')
    op.drop_index(op.f('ix_health_recommendation_cache_recommendation_key'), table_name='health_recommendation_cache')
    op.drop_index(op.f('ix_health_recommendation_cache_patient_hash'), table_name='health_recommendation_cache')
    op.drop_index(op.f('ix_health_recommendation_cache_id'), table_name='health_recommendation_cache')
    op.drop_table('health_recommendation_cache')
    op.drop_index(op.f('ix_guardian_alert_settings_patient_hash'), table_name='guardian_alert_settings')
    op.drop_index(op.f('ix_guardian_alert_settings_id'), table_name='guardian_alert_settings')
    op.drop_index(op.f('ix_guardian_alert_settings_guardian_hash'), table_name='guardian_alert_settings')
    op.drop_table('guardian_alert_settings')
    op.drop_index(op.f('ix_drug_basic_infos_normalized_item_name'), table_name='drug_basic_infos')
    op.drop_index(op.f('ix_drug_basic_infos_item_seq'), table_name='drug_basic_infos')
    op.drop_index(op.f('ix_drug_basic_infos_item_name'), table_name='drug_basic_infos')
    op.drop_index(op.f('ix_drug_basic_infos_id'), table_name='drug_basic_infos')
    op.drop_table('drug_basic_infos')
    op.drop_index(op.f('ix_drug_approval_infos_normalized_item_name'), table_name='drug_approval_infos')
    op.drop_index(op.f('ix_drug_approval_infos_item_seq'), table_name='drug_approval_infos')
    op.drop_index(op.f('ix_drug_approval_infos_item_name'), table_name='drug_approval_infos')
    op.drop_index(op.f('ix_drug_approval_infos_id'), table_name='drug_approval_infos')
    op.drop_table('drug_approval_infos')
    # ### end Alembic commands ###
