name: Flutter CI

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Source Code Checkout
      uses: actions/checkout@v4

    - name: Java Setup (for Flutter)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter Setup
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.41.5'
        channel: 'stable'

    - name: Package Get
      run: flutter pub get

    - name: Dart Code Analysis
      run: flutter analyze

    - name: Run Flutter Tests
      run: flutter test

      # build까지 필요없을 때 주석처리 요망
    - name: Android APK Build Test
      run: flutter build apk --debug